from .constant import Constant
from .local_variable import LocalIRVariable
from .reference import ReferenceVariable
from .reference_ssa import ReferenceVariableSSA
from .state_variable import StateIRVariable
from .temporary import TemporaryVariable
from .temporary_ssa import TemporaryVariableSSA
from .tuple import TupleVariable
from .tuple_ssa import TupleVariableSSA
