--- 
body: 
  - 
    attributes: 
      value: |
          Please check the issues tab to avoid duplicates. 
          Thanks for helping make Slither the best it can be!
    type: markdown
  - 
    attributes: 
      label: "Describe the false alarm that Slither raise and how you know it's inaccurate:"
    id: what-happened
    type: textarea
    validations: 
      required: true
  - 
    attributes:
      label: Frequency
      description: How often do you run across this false positive?
      options:
        - Very Frequently
        - Occasionally 
        - Rarely
        - Not sure
    id: frequency
    type: dropdown
    validations:
      required: true
  - 
    attributes: 
      description: "It can be a github repo, etherscan link, or code snippet."
      label: "Code example to reproduce the issue:"
      placeholder: "`contract A {}`\n"
    id: reproduce
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: |
          What version of slither are you running? 
          Run `slither --version`
      label: "Version:"
    id: version
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: |
          Please copy and paste the result output. This 
          will be automatically formatted into code, so no need for backticks.
      render: shell
      label: "Relevant log output:"
    id: logs
    type: textarea
description: "Slither warned of an issue that is not legitimate and does not need to be fixed."
labels: 
  - false-positive
name: "False Positive"
title: "[False-Positive]: "
