# Serena project configuration for slither
languages:
- python
roots:
- slither
- tests

# Ignore generated/vendored/cache directories
ignore:
- ".git"
- ".venv"
- "__pycache__"
- "*.egg-info"
- "*.pyc"
- "build"
- "dist"
- ".ruff_cache"
- ".mypy_cache"
- ".pytest_cache"
- ".tox"
- ".hypothesis"
- "htmlcov"
- "crytic-export"
- "test_artifacts"
- "tests/e2e/**/snapshots"
- ".idea"
- ".vscode"
- ".worktrees"
- "docs/_build"

# Allow Serena to make edits (vs read-only mode)
allow_write: true

# Disable tools that are redundant with Claude Code or not needed
excluded_tools:
- onboarding
- check_onboarding_performed
- list_dir
- find_file

# initial prompt for the project. It will always be given to the LLM upon activating the project
# (contrary to the memories, which are loaded on demand).
initial_prompt: |
  This project has a comprehensive CLAUDE.md with architecture, code standards,
  and Slither-specific patterns. Refer to it for project context rather than
  using onboarding or memories.

# list of mode names to that are always to be included in the set of active modes
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the base_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this setting overrides the global configuration.
# Set this to [] to disable base modes for this project.
# Set this to a list of mode names to always include the respective modes for this project.
base_modes:

# list of mode names that are to be activated by default.
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the default_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this overrides the setting from the global configuration (serena_config.yml).
# This setting can, in turn, be overridden by CLI parameters (--mode).
default_modes:

# list of tools to include that would otherwise be disabled (particularly optional tools that are disabled by default)
included_optional_tools: []

# fixed set of tools to use as the base tool set (if non-empty), replacing Serena's default set of tools.
# This cannot be combined with non-empty excluded_tools or included_optional_tools.
fixed_tools: []

# list of additional paths to ignore in all projects
# same syntax as gitignore, so you can use * and **
ignored_paths: []

# whether the project is in read-only mode
# If set to true, all editing tools will be disabled and attempts to use them will result in an error
# Added on 2025-04-18
read_only: false

# whether to use project's .gitignore files to ignore files
ignore_all_files_in_gitignore: true

# the encoding used by text files in the project
# For a list of possible encodings, see https://docs.python.org/3.11/library/codecs.html#standard-encodings
encoding: utf-8
# the name by which the project can be referenced within Serena
project_name: slither
