---
name: Doctor

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'slither/tools/doctor/**'
      - '.github/workflows/doctor.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  slither-doctor:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-2025"]
        python: ["3.10", "3.14"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: ${{ matrix.python }}

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
        with:
          enable-cache: true

      - name: Try system-wide Slither
        run: |
          echo "::group::Install slither"
          uv pip install --system .
          echo "::endgroup::"

          # escape cwd so python doesn't pick up local module
          cd /

          echo "::group::Via module"
          python3 -m slither.tools.doctor "$GITHUB_WORKSPACE"
          echo "::endgroup::"

          echo "::group::Via binary"
          slither-doctor "$GITHUB_WORKSPACE"
          echo "::endgroup::"

      - name: Try venv Slither
        run: |
          echo "::group::Install slither"
          uv venv
          uv pip install .
          source .venv/bin/activate || source .venv/Scripts/activate
          hash -r
          echo "::endgroup::"

          # escape cwd so python doesn't pick up local module
          cd /

          echo "::group::Via module"
          python3 -m slither.tools.doctor "$GITHUB_WORKSPACE"
          echo "::endgroup::"

          echo "::group::Via binary"
          slither-doctor "$GITHUB_WORKSPACE"
          echo "::endgroup::"
