---
name: IR tests

defaults:
  run:
    # To load bashrc
    shell: bash -ieo pipefail {0}

on:
  pull_request:
    branches: [master, dev]
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron: '0 12 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: IR tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2022]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install ".[dev]"
          solc-select install 0.5.0         
          solc-select use 0.8.11 --always-install

      - name: Install old solc
        if: matrix.os == 'ubuntu-latest'
        run: solc-select install 0.4.0


      - name: Test with pytest
        run: |
          pytest tests/test_ssa_generation.py