---
name: Lint Code Base

defaults:
  run:
    # To load bashrc
    shell: bash -ieo pipefail {0}

on:
  pull_request:
    branches: [master, dev]
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron: '0 12 * * *'

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v3
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          pip install .
          pip install deepdiff numpy

          mkdir -p .github/linters
          cp pyproject.toml .github/linters

      - name: Pylint
        uses: github/super-linter/slim@v4
        if: always()
        env:
          # run linter on everything to catch preexisting problems
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Run only pylint
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_PYLINT: true
          PYTHON_PYLINT_CONFIG_FILE: pyproject.toml
          FILTER_REGEX_EXCLUDE: .*tests/.*.(json|zip|sol)
